# Generated by Django 2.1.11 on 2019-12-10 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeLancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('family', models.CharField(max_length=255, verbose_name='Family')),
                ('father_name', models.CharField(max_length=255, verbose_name='Father Name')),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FreeLancer',
                'verbose_name_plural': 'FreeLancers',
            },
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
